### ISSUE TITLE
Do you have plan to decompile Artifact to get all database after game release?

### ISSUE THREAD

**Issue by pengzh0928** [Desvelao/artifact-database#1]
Thanks for you maintain this database manually.  After game is released, I guess we could find the whole database by decompile it. 

In that time, maybe we can make a tool, which can convert game original database to this Json struct.

**Comment by Desvelao** [comment]
It would be amazing if we could extract the data with a app!. This repository is maintained manually at the moment. Sorry for reply after some days, i didn't see a issue because i thought this repository wouldn't get visibility. I am using this data for a Discord bot. I have other repository with assets for the game (card types, and card images atm) if you are interested @DJDGSFTX

**Comment by pengzh0928** [comment]
Yes, I am interested in that.  I also want to maintain a Artifact Database (include cards information and images). Maybe we can use the same image repository.
